skeleton_data:
  joint_connections:
    - [11,12]
    - [11,13]
    - [11,23]
    - [12,14]
    - [12,24]
    - [13,15]
    - [14,16]
    - [23,24]
    - [23,25]
    - [24,26]
    - [25,27]
    - [26,28]
  colors:
    - [1,0,0]
    - [0,1,0]
    - [0,0,1]

floor:
 y: -100

camera:
  speed: 10